#!/usr/bin/env sh

# Refrence:
# https://github.com/koekeishiya/yabai/wiki/Commands#message-passing-interface

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa

# TODO: think of bounding apps to spaces. Reference: https://github.com/koekeishiya/yabai/issues/1387

# global settings
yabai -m config                          \
    menubar_opacity      1.0             \
    mouse_follows_focus off              \
    focus_follows_mouse off              \
    display_arrangement_order default    \
    window_origin_display default        \
    window_placement second_child        \
    window_zoom_persist off              \
    window_shadow on                     \
    window_animation_duration 0.0        \
    window_animation_frame_rate 120      \
    window_opacity_duration 0.0          \
    active_window_opacity 1.0            \
    normal_window_opacity 1.0            \
    window_opacity off                   \
    insert_feedback_color 0xffd75f5f     \
    split_ratio 0.50                     \
    split_type auto                      \
    auto_balance off                     \
    top_padding 10                       \
    bottom_padding 10                    \
    left_padding 10                      \
    right_padding 10                     \
    window_gap 10                        \
    layout bsp                           \
    mouse_modifier fn                    \
    mouse_action1 move                   \
    mouse_action2 resize                 \
    mouse_drop_action swap               \
    external_bar all:48:0

# exclude apps from tiling
yabai -m rule --add app="^(Cisco.*|Shottr|Preview|Raycast|System Settings|System Information|Activity Monitor|Calculator)$" manage=off

# trigger sketchybar action on window event
yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

# stop/start/restart yabai
ctrl + alt - q : yabai --stop-service
ctrl + alt - s : yabai --start-service
ctrl + alt - r : yabai --restart-service

echo "yabai configuration loaded..."
