[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
#decorations = "None"
