import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
#decorations = "None"
